version: '3.7'

networks:
  consignado:
    driver: bridge

services:
  simulacao:
    container_name: simulacao_microservice
    command: dockerize -wait tcp://mysql:3306 -timeout 180s java -jar app.jar
    build: ./simulacao
    environment:
      - DATABASE_MYSQL_URL=mysql:3306
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - consignado

  custodia:
    container_name: custodia_microservice
    command: dockerize -wait tcp://mysql:3306 -timeout 180s java -jar app.jar
    build: ./custodia
    environment:
      - DATABASE_MYSQL_URL=mysql:3306
      - CONSIGNADO_SIMULACAO_API=simulacao-simulacao
    depends_on:
      - mysql
    ports:
      - 8081:8081
    networks:
      - consignado
      
  consul:
    image: hashicorp/consul:latest
    command: ["consul", "agent", "-dev", "-client", "0.0.0.0"]
    ports:
      - 8500:8500
    networks:
      - consignado

  mysql:
    container_name: simulacao_database
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=simulacao
    ports:
      - 3306:3306
    networks:
      - consignado
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
